### ISSUE TITLE
Why does the documentation talk about xc3sprog?

### ISSUE THREAD

**Issue by mithro** [chipsalliance/f4pga#368]
The tool we are generally using for doing bitstream loading is OpenOCD (which is also what is packaged in conda and referenced by cmake) yet the instructions at https://symbiflow.readthedocs.io/en/latest/symbiflow-arch-defs/docs/source/getting-started.html#load-bitstream don't talk about OpenOCD at all? (Also it doesn't mention where or how to get xc3sprog either?)

**Comment by umarcor** [comment]
Closing because the docs were updated and they don't talk about xc3sprog anymore:

- https://github.com/SymbiFlow/f4pga-arch-defs/pull/2233
- https://github.com/SymbiFlow/f4pga-arch-defs/pull/2240
