### ISSUE TITLE
Documentation should provide directions to get latest arch-defs?

### ISSUE THREAD

**Issue by litghost** [chipsalliance/f4pga#429]
We have public URLs to the latest arch-defs, e.g. https://storage.googleapis.com/symbiflow-arch-defs-gha/symbiflow-xc7a50t_test-latest , but I don't believe we have an documentation or scripts to use that URL?

**Comment by umarcor** [comment]
This is now explained in https://f4pga.readthedocs.io/en/latest/getting-started.html#conda-recommended (see the note and also https://f4pga.readthedocs.io/en/latest/getting-started.html#bumping-overriding-specific-tools), which links to https://f4pga.readthedocs.io/projects/arch-defs/en/latest/packages.html#packages.
