### ISSUE TITLE
Document the need for F4PGA_INSTALL_DIR environmental variable for new python module

### ISSUE THREAD

**Issue by Pocketkid2** [chipsalliance/f4pga#562]
In line 57 of [\_\_init\_\_.py](https://github.com/chipsalliance/f4pga/blob/a6f19c029fcd0d1fb99eb44c6881e51c25b3dd51/f4pga/__init__.py) the share dir is read from the environment variable called F4PGA_INSTALL_DIR, and defaults to /usr/local if not found. I am not aware of any documentation that instructs the user to create this variable, as previous symbiflow/f4pga installs that I am aware of will only have a variable called INSTALL_DIR. (For example, [f4pga-examples install](https://f4pga-examples.readthedocs.io/en/latest/getting.html#choose-the-install-directory)

Not having this proper environmental variable tripped up me and my work partner because we were not expecting that the module was expecting this new variable, and our default install path was not /usr/local, but rather ~/opt/f4pga.

**Comment by umarcor** [comment]
The documentation now explains that the envvar is required (https://f4pga.readthedocs.io/en/latest/getting-started.html#conda-recommended). It is now consistent with the envvar used in f4pga-examples. Furthermore, the code raises an explicit exception if it is not defined: https://github.com/chipsalliance/f4pga/blob/main/f4pga/wrappers/sh/__init__.py#L37-L38.
